const GAME=document.getElementById('game');
const PLAYER=document.getElementById('player'), ENEMY=document.getElementById('enemy');
const PLAYER_IMG=document.getElementById('playerImg'), ENEMY_IMG=document.getElementById('enemyImg');
const VFX_BACK=document.getElementById('vfxBackLayer'), VFX_FRONT=document.getElementById('vfxFrontLayer'), PROJECTILES=document.getElementById('projectileLayer');
const playerHp=document.getElementById('playerHp'), enemyHp=document.getElementById('enemyHp');
const path=n=>'./assets/'+n;
const sprites={p:{idle:['rex_idle0.webp','rex_idle1.webp'],run:['rex_run0.webp','rex_run1.webp'],jump:'rex_jump.webp',fall:'rex_fall.webp',attack:['rex_attack0.webp','rex_attack1.webp'],special:'rex_special.webp'},e:{idle:['aion_idle0.webp'],hit:'aion_hit.webp'}};
const fx={slash:'fx_fire_slash.webp',shot:'fx_blast_fire.webp',hit:'fx_hit_orange.webp'};
const input={x:0,left:false,right:false};
const FIXED=1/120;
let last=performance.now(),acc=0,projectiles=[];
const state={p:{x:.30,y:.68,prevX:.30,prevY:.68,vx:0,vy:0,on:true,jumps:2,attack:0,special:0,face:1},e:{x:.72,y:.68,hp:100,hit:0},php:100};
function rect(){const r=GAME.getBoundingClientRect();return{w:r.width,h:r.height}}
function setSrc(img,src){if(img.dataset.src!==src){img.src=path(src);img.dataset.src=src}}
function pxPos(nx,ny){const r=rect();return{x:nx*r.w,y:ny*r.h}}
function safeFx(nx,ny,size){const r=rect(),p=pxPos(nx,ny),half=size*.52,margin=8;return{x:Math.max(half+margin,Math.min(r.w-half-margin,p.x)),y:Math.max(half+margin,Math.min(r.h-half-margin,p.y))}}
function spawnFx(layer,src,nx,ny,size,rot=0,special=false){const r=rect();const max=Math.min(r.w,r.h);const s=Math.min(size,max*.36);const p=safeFx(nx,ny,s);const d=document.createElement('div');d.className='fx'+(special?' specialFx':'');d.style.left=p.x+'px';d.style.top=p.y+'px';d.style.width=s+'px';d.style.height=s+'px';d.style.setProperty('--rot',rot+'deg');const im=document.createElement('img');im.src=path(src);d.appendChild(im);layer.appendChild(d);setTimeout(()=>d.remove(),special?440:320)}
function ring(nx,ny,size,color){const p=safeFx(nx,ny,size),d=document.createElement('div');d.className='ring';d.style.left=p.x+'px';d.style.top=p.y+'px';d.style.width=size+'px';d.style.height=size+'px';d.style.borderColor=color;d.style.boxShadow=`0 0 18px ${color}`;VFX_FRONT.appendChild(d);setTimeout(()=>d.remove(),270)}
function pop(nx,ny,val){const p=pxPos(nx,ny),d=document.createElement('div');d.className='damagePop';d.style.left=p.x+'px';d.style.top=p.y+'px';d.textContent='+'+val;VFX_FRONT.appendChild(d);setTimeout(()=>d.remove(),540)}
function hitEnemy(amount,blue=false){if(state.e.hit>0)return;state.e.hp=Math.max(0,state.e.hp-amount);state.e.hit=.22;enemyHp.style.width=state.e.hp+'%';spawnFx(VFX_FRONT,fx.hit,state.e.x,state.e.y-.15,blue?112:98,0,blue);ring(state.e.x,state.e.y-.15,blue?72:60,blue?'rgba(113,220,255,.9)':'rgba(255,218,112,.9)');pop(state.e.x,state.e.y-.20,amount)}
function attack(){if(state.p.attack>0||state.p.special>0)return;state.p.attack=.28;const nx=state.p.x+state.p.face*.085;ring(nx-state.p.face*.012,state.p.y-.16,54,'rgba(255,180,85,.72)');spawnFx(VFX_BACK,fx.slash,nx,state.p.y-.165,112,state.p.face<0?180:0,false);if(Math.abs(state.e.x-state.p.x)<.215)hitEnemy(9,false)}
function special(){if(state.p.attack>0||state.p.special>0)return;state.p.special=.42;ring(state.p.x+state.p.face*.02,state.p.y-.16,66,'rgba(255,180,85,.82)');setTimeout(()=>{projectiles.push({x:state.p.x+state.p.face*.095,y:state.p.y-.16,vx:state.p.face*.58,el:null})},80)}
function jump(){const p=state.p;if(p.on){p.vy=-.74;p.on=false;p.jumps=1;return}if(p.jumps>0){p.vy=-.68;p.jumps--;}}
function fixedUpdate(dt){const p=state.p;p.prevX=p.x;p.prevY=p.y;const m=Math.abs(input.x)>.06?input.x:((input.right?1:0)-(input.left?1:0));if(Math.abs(m)>.06){p.face=m>0?1:-1;p.vx+=m*1.45*dt;p.vx=Math.max(-.52,Math.min(.52,p.vx))}else p.vx*=Math.pow(.0008,dt);p.vy+=1.72*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.y>=.68){p.y=.68;p.vy=0;p.on=true;p.jumps=2}p.x=Math.max(.18,Math.min(.58,p.x));if(p.attack>0)p.attack=Math.max(0,p.attack-dt);if(p.special>0)p.special=Math.max(0,p.special-dt);if(state.e.hit>0)state.e.hit=Math.max(0,state.e.hit-dt);updateProjectiles(dt)}
function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const q=projectiles[i];q.x+=q.vx*dt;const p=pxPos(q.x,q.y);if(!q.el){q.el=document.createElement('div');q.el.className='projectile';const im=document.createElement('img');im.src=path(fx.shot);q.el.appendChild(im);PROJECTILES.appendChild(q.el)}q.el.style.transform=`translate3d(${p.x}px,${p.y}px,0) translate(-50%,-50%)`;if((performance.now()/42|0)%2===0){const t=document.createElement('div');t.className='trail';t.style.left=p.x+'px';t.style.top=p.y+'px';t.style.width='12px';t.style.height='12px';t.style.background='radial-gradient(circle,#ffd66a,#ff6b43 65%,transparent 72%)';PROJECTILES.appendChild(t);setTimeout(()=>t.remove(),220)}if(Math.abs(q.x-state.e.x)<.06){hitEnemy(13,true);spawnFx(VFX_FRONT,fx.shot,q.x,q.y,104,0,true);q.el.remove();projectiles.splice(i,1);continue}if(q.x<-.1||q.x>1.1){q.el.remove();projectiles.splice(i,1)}}}
function frame(){const p=state.p;if(p.special>0)return sprites.p.special;if(p.attack>0)return p.attack>.14?sprites.p.attack[0]:sprites.p.attack[1];if(!p.on)return p.vy<0?sprites.p.jump:sprites.p.fall;if(Math.abs(p.vx)>.06)return(performance.now()/78|0)%2?sprites.p.run[0]:sprites.p.run[1];return(performance.now()/210|0)%2?sprites.p.idle[0]:sprites.p.idle[1]}
function render(alpha){const r=rect(),p=state.p,e=state.e;setSrc(PLAYER_IMG,frame());setSrc(ENEMY_IMG,state.e.hit>0?sprites.e.hit:sprites.e.idle[0]);const pw=PLAYER.offsetWidth,ph=PLAYER.offsetHeight,ew=ENEMY.offsetWidth,eh=ENEMY.offsetHeight;const rx=p.prevX+(p.x-p.prevX)*alpha,ry=p.prevY+(p.y-p.prevY)*alpha;const px=rx*r.w-pw*.5,py=ry*r.h-ph*.79;const ex=e.x*r.w-ew*.5,ey=e.y*r.h-eh*.79;const speed=Math.min(1,Math.abs(p.vx)/.52);const bob=p.on&&speed>.08?Math.sin(performance.now()/72)*speed*1.6:0;const lean=p.face*Math.min(4,Math.abs(p.vx)*8);PLAYER.style.transform=`translate3d(${px}px,${py+bob}px,0) scaleX(${p.face}) rotate(${lean}deg)`;ENEMY.style.transform=`translate3d(${ex}px,${ey}px,0)`;ENEMY.classList.toggle('hitFlash',e.hit>0)}
function loop(t){let frameDt=Math.min(.05,(t-last)/1000||.016);last=t;acc+=frameDt;let guard=0;while(acc>=FIXED&&guard<8){fixedUpdate(FIXED);acc-=FIXED;guard++}render(Math.min(1,acc/FIXED));requestAnimationFrame(loop)}
const sb=document.getElementById('stickBase'),sk=document.getElementById('stickKnob');let active=false,rad=1;function refresh(){rad=sb.getBoundingClientRect().width*.28}function moveStick(e){const r=sb.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=e.clientX-cx,dy=e.clientY-cy,d=Math.hypot(dx,dy)||1;if(d>rad){dx=dx/d*rad;dy=dy/d*rad}sk.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`;input.x=Math.abs(dx/rad)<.06?0:Math.max(-1,Math.min(1,dx/rad))}function reset(){active=false;input.x=0;sk.style.transform='translate(-50%,-50%)'}refresh();addEventListener('resize',refresh);sb.onpointerdown=e=>{active=true;sb.setPointerCapture(e.pointerId);moveStick(e)};sb.onpointermove=e=>{if(active)moveStick(e)};sb.onpointerup=reset;sb.onpointercancel=reset;sb.onlostpointercapture=reset;
document.getElementById('jumpBtn').onpointerdown=e=>{e.preventDefault();jump()};document.getElementById('attackBtn').onpointerdown=e=>{e.preventDefault();attack()};document.getElementById('specialBtn').onpointerdown=e=>{e.preventDefault();special()};addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='a'||k==='arrowleft')input.left=true;if(k==='d'||k==='arrowright')input.right=true;if(k==='w'||k==='arrowup'||k===' ')jump();if(k==='j'||k==='z')attack();if(k==='k'||k==='x')special()});addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k==='a'||k==='arrowleft')input.left=false;if(k==='d'||k==='arrowright')input.right=false});playerHp.style.width='100%';enemyHp.style.width='100%';requestAnimationFrame(loop);
